-- Normalized Oracle schema for Marketplace
-- Keeps the app-compatible summary columns, but normalizes roles and child tables.

CREATE TABLE roles (
    role_name VARCHAR2(20) PRIMARY KEY
);

INSERT INTO roles (role_name) VALUES ('USER');
INSERT INTO roles (role_name) VALUES ('ADMIN');

CREATE TABLE users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50) NOT NULL UNIQUE,
    email         VARCHAR2(100) NOT NULL UNIQUE,
    password      VARCHAR2(255) NOT NULL,
    role          VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    created_at    DATE DEFAULT SYSDATE,
    CONSTRAINT fk_users_role
        FOREIGN KEY (role)
        REFERENCES roles(role_name)
);

CREATE TABLE categories (
    category_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name       VARCHAR2(100) NOT NULL UNIQUE,
    parent_category_id  NUMBER,
    CONSTRAINT fk_parent_category
        FOREIGN KEY (parent_category_id)
        REFERENCES categories(category_id)
);

CREATE TABLE items (
    item_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_user_id  NUMBER NOT NULL,
    category_id     NUMBER NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    description     CLOB,
    price           NUMBER(10,2) CHECK (price > 0),
    quantity        NUMBER DEFAULT 1 CHECK (quantity >= 0),
    avg_rating      NUMBER(2,1) DEFAULT 0 CHECK (avg_rating BETWEEN 0 AND 5),
    review_count    NUMBER DEFAULT 0,
    status          VARCHAR2(20) DEFAULT 'AVAILABLE',
    created_at      DATE DEFAULT SYSDATE,
    CONSTRAINT fk_item_seller
        FOREIGN KEY (seller_user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_item_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),
    CONSTRAINT chk_item_status
        CHECK (status IN ('AVAILABLE', 'SOLD', 'REMOVED'))
);

CREATE TABLE item_images (
    image_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id     NUMBER NOT NULL,
    image_url   VARCHAR2(500) NOT NULL,
    uploaded_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_image_item
        FOREIGN KEY (item_id)
        REFERENCES items(item_id)
        ON DELETE CASCADE
);

CREATE TABLE cart (
    cart_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL,
    item_id      NUMBER NOT NULL,
    quantity     NUMBER DEFAULT 1 CHECK (quantity > 0),
    added_at     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_cart_item
        FOREIGN KEY (item_id)
        REFERENCES items(item_id),
    CONSTRAINT unique_user_item
        UNIQUE (user_id, item_id)
);

CREATE TABLE orders (
    order_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL,
    item_id        NUMBER NOT NULL,
    quantity       NUMBER NOT NULL CHECK (quantity > 0),
    total_amount   NUMBER(10,2),
    status         VARCHAR2(30) DEFAULT 'PAYMENT_PENDING',
    tracking_id    VARCHAR2(100),
    order_date     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_order_item
        FOREIGN KEY (item_id)
        REFERENCES items(item_id),
    CONSTRAINT chk_order_status
        CHECK (status IN (
            'PAYMENT_PENDING',
            'ORDERED',
            'PROCESSING',
            'SHIPPED',
            'OUT_FOR_DELIVERY',
            'DELIVERED',
            'CANCELLED'
        ))
);

CREATE TABLE alerts (
    alert_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL,
    category_id  NUMBER,
    item_id      NUMBER,
    created_at   DATE DEFAULT SYSDATE,
    CONSTRAINT fk_alert_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_alert_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),
    CONSTRAINT fk_alert_item
        FOREIGN KEY (item_id)
        REFERENCES items(item_id)
);

CREATE TABLE reviews (
    review_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL,
    item_id      NUMBER NOT NULL,
    rating       NUMBER(2,1) CHECK (rating BETWEEN 0 AND 5),
    review_text  CLOB,
    created_at   DATE DEFAULT SYSDATE,
    CONSTRAINT fk_review_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_review_item
        FOREIGN KEY (item_id)
        REFERENCES items(item_id),
    CONSTRAINT unique_user_review
        UNIQUE (user_id, item_id)
);

CREATE TABLE grievances (
    grievance_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    order_id        NUMBER,
    item_id         NUMBER,
    problem_desc    CLOB,
    problem_status  VARCHAR2(20) DEFAULT 'UNRESOLVED',
    admin_reply     CLOB,
    replied_at      DATE,
    replied_by      NUMBER,
    created_at      DATE DEFAULT SYSDATE,
    CONSTRAINT fk_grievance_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_grievance_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_grievance_item
        FOREIGN KEY (item_id)
        REFERENCES items(item_id),
    CONSTRAINT fk_grievance_replied_by
        FOREIGN KEY (replied_by)
        REFERENCES users(user_id),
    CONSTRAINT chk_problem_status
        CHECK (problem_status IN ('RESOLVED','UNRESOLVED'))
);

CREATE TABLE grievance_images (
    grievance_image_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grievance_id       NUMBER NOT NULL,
    image_url          VARCHAR2(500) NOT NULL,
    uploaded_at        DATE DEFAULT SYSDATE,
    CONSTRAINT fk_grievance_image_grievance
        FOREIGN KEY (grievance_id)
        REFERENCES grievances(grievance_id)
        ON DELETE CASCADE
);

CREATE TABLE payments (
    payment_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              NUMBER NOT NULL,
    stripe_payment_intent VARCHAR2(200) UNIQUE,
    stripe_session_id     VARCHAR2(200),
    amount                NUMBER(10,2) NOT NULL,
    currency              VARCHAR2(10) DEFAULT 'INR',
    payment_status        VARCHAR2(30) DEFAULT 'PENDING',
    created_at            DATE DEFAULT SYSDATE,
    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT chk_payment_status
        CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE TABLE user_interests (
    interest_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category_id NUMBER,
    min_price NUMBER,
    max_price NUMBER,
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_user_interest_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_interest_category
        FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE password_resets (
    reset_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL,
    reset_token   VARCHAR2(255) NOT NULL,
    expires_at    DATE NOT NULL,
    created_at    DATE DEFAULT SYSDATE,
    CONSTRAINT fk_reset_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_items_category ON items(category_id);
CREATE INDEX idx_items_seller ON items(seller_user_id);
CREATE INDEX idx_cart_user ON cart(user_id);
CREATE INDEX idx_images_item ON item_images(item_id);
CREATE INDEX idx_reviews_item ON reviews(item_id);
CREATE INDEX idx_payments_order ON payments(order_id);
